package com.alexander.carplay.platform.service

import android.content.Intent
import android.os.Build
import android.content.Context
import android.media.MediaMetadata
import android.media.session.MediaSession
import android.media.session.PlaybackState
import android.view.KeyEvent
import com.alexander.carplay.data.logging.DiagnosticLogStore
import com.alexander.carplay.domain.model.NowPlayingSnapshot

/**
 * Holds an active [MediaSession] while CarPlay is streaming.
 *
 * When active, Android routes Bluetooth AVRCP transport commands through this
 * session instead of forwarding them directly to a paired iPhone via the
 * system Bluetooth connection. This prevents the iPhone from switching away
 * from CarPlay audio mode in response to AVRCP "play" events generated by
 * the Android media stack.
 */
class CarPlayMediaSession(
    context: Context,
    private val logStore: DiagnosticLogStore,
) {
    companion object {
        private const val SOURCE = "MediaSessionFix"
        private const val SESSION_TAG = "CarPlayAudio"
    }

    private val appContext = context.applicationContext

    private var session: MediaSession? = null

    private val callback = object : MediaSession.Callback() {
        override fun onPlay() {
            logStore.info(SOURCE, "MediaSession callback: onPlay")
        }

        override fun onPause() {
            logStore.info(SOURCE, "MediaSession callback: onPause")
        }

        override fun onStop() {
            logStore.info(SOURCE, "MediaSession callback: onStop")
        }

        override fun onSkipToNext() {
            logStore.info(SOURCE, "MediaSession callback: onSkipToNext")
        }

        override fun onSkipToPrevious() {
            logStore.info(SOURCE, "MediaSession callback: onSkipToPrevious")
        }

        override fun onMediaButtonEvent(mediaButtonIntent: Intent): Boolean {
            val keyEvent = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
                mediaButtonIntent.getParcelableExtra(Intent.EXTRA_KEY_EVENT, KeyEvent::class.java)
            } else {
                @Suppress("DEPRECATION")
                mediaButtonIntent.getParcelableExtra(Intent.EXTRA_KEY_EVENT)
            }
            logStore.info(
                SOURCE,
                "MediaSession callback: onMediaButtonEvent " +
                    "action=${keyEvent?.action ?: "-"} key=${keyEvent?.keyCode?.let(KeyEvent::keyCodeToString) ?: "-"}",
            )
            return super.onMediaButtonEvent(mediaButtonIntent)
        }
    }

    private val activeState: PlaybackState = PlaybackState.Builder()
        .setState(PlaybackState.STATE_PLAYING, 0L, 1f)
        .setActions(
            PlaybackState.ACTION_PLAY or
                PlaybackState.ACTION_PAUSE or
                PlaybackState.ACTION_STOP,
        )
        .build()

    private val inactiveState: PlaybackState = PlaybackState.Builder()
        .setState(PlaybackState.STATE_STOPPED, 0L, 1f)
        .setActions(0L)
        .build()

    fun activate() {
        if (session?.isActive == true) return
        val s = session ?: MediaSession(appContext, SESSION_TAG).also {
            it.setCallback(callback)
            session = it
        }
        s.setPlaybackState(activeState)
        s.isActive = true
        logStore.info(SOURCE, "MediaSession activated")
    }

    fun deactivate() {
        val s = session ?: return
        if (!s.isActive) return
        s.setPlaybackState(inactiveState)
        s.isActive = false
        logStore.info(SOURCE, "MediaSession deactivated")
    }

    fun release() {
        session?.let {
            it.isActive = false
            it.release()
        }
        session = null
        logStore.info(SOURCE, "MediaSession released")
    }

    fun updateMetadata(snapshot: NowPlayingSnapshot) {
        val s = session ?: return
        val metadata = MediaMetadata.Builder().apply {
            snapshot.songName?.let { putString(MediaMetadata.METADATA_KEY_TITLE, it) }
            snapshot.artistName?.let { putString(MediaMetadata.METADATA_KEY_ARTIST, it) }
            snapshot.albumName?.let { putString(MediaMetadata.METADATA_KEY_ALBUM, it) }
            snapshot.durationSeconds?.let { putLong(MediaMetadata.METADATA_KEY_DURATION, it * 1000L) }
        }.build()
        s.setMetadata(metadata)
        val isPlaying = snapshot.playStatus == 1
        val playbackPosition = (snapshot.playTimeSeconds ?: 0) * 1000L
        val updatedState = PlaybackState.Builder()
            .setState(
                if (isPlaying) PlaybackState.STATE_PLAYING else PlaybackState.STATE_PAUSED,
                playbackPosition,
                1f,
            )
            .setActions(
                PlaybackState.ACTION_PLAY or
                    PlaybackState.ACTION_PAUSE or
                    PlaybackState.ACTION_STOP,
            )
            .build()
        s.setPlaybackState(updatedState)
        logStore.info(
            SOURCE,
            "MediaSession metadata updated: title=${snapshot.songName} artist=${snapshot.artistName} " +
                "status=${snapshot.playStatus} pos=${snapshot.playTimeSeconds}s dur=${snapshot.durationSeconds}s",
        )
    }

    fun clearMetadata() {
        val s = session ?: return
        s.setMetadata(MediaMetadata.Builder().build())
        s.setPlaybackState(activeState)
        logStore.info(SOURCE, "MediaSession metadata cleared")
    }

    fun isActive(): Boolean = session?.isActive == true
}
